stages:
  - build_staging
  - deploy_staging
  - build_production
  - deploy_production

variables:
    SERVICE_NAME_STAGING: staging
    SERVICE_NAME_PRODUCTION: production
    IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.8-dind
    command: ["--mtu=1440"]

build_staging:
  stage: build_staging
  image: docker:19.03.8
  environment:
    name: staging
    url: https://staging.bendingtherules.nl
  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker pull ${IMAGE} || true
    - docker build --cache-from ${IMAGE} -t ${IMAGE} -f ./Dockerfile .
    - docker push ${IMAGE}

deploy_staging:
    stage: deploy_staging
    image: dtzar/helm-kubectl:2.16.1
    environment:
      name: staging
      url: https://staging.bendingtherules.nl
    only:
      - develop
      - master
    script:
      - sed -i -e "s@CURRENT_DATE@\"$(date +'%s')\"@" k8s/deploy.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_STAGING@" k8s/deploy.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_STAGING@" k8s/ingress.yaml
      - sed -i -e "s@SERVICE_URL@$SERVICE_NAME_STAGING.bendingtherules.nl@" k8s/ingress.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_STAGING@" k8s/service.yaml
      - sed -i -e "s@DOCKER_IMAGE@$IMAGE@" k8s/deploy.yaml
      - kubectl delete secret wildcard-bending-the-rules-nl-secret || true
      - kubectl delete secret gitlab-docker-registry || true
      - kubectl create secret docker-registry gitlab-docker-registry --docker-server=registry.bendingtherules.nl --docker-username=kubernetes --docker-password=${KUBERNETES_DOCKER_PASSWORD} --docker-email=kubernetes@bendingtherules.nl -n ${KUBE_NAMESPACE}
      - kubectl replace -f k8s/deploy.yaml || kubectl create -f k8s/deploy.yaml
      - kubectl apply   -f k8s/service.yaml
      - kubectl apply   -f k8s/ingress.yaml

build_production:
  image: node:12.16.2-alpine3.11
  stage: build_production
  environment:
    name: build_production
    url: https://bendingtherules.nl
  only:
    - master
  variables:
    CONFIGURATION: TST
  artifacts:
    expire_in: 1 week
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
      - build
  script:
    - npm install --silent
    - npm install react-scripts@3.0.1 -g --silent
    - npm run build

deploy_production:
    stage: deploy_production
    image: dtzar/helm-kubectl:2.16.1
    environment:
      name: deploy_production
      url: https://bendingtherules.nl
    only:
      - master
    script:
      - sed -i -e "s@CURRENT_DATE@\"$(date +'%s')\"@" k8s/deploy.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_PRODUCTION@" k8s/deploy.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_PRODUCTION@" k8s/ingress.yaml
      - sed -i -e "s@SERVICE_URL@bendingtherules.nl@" k8s/ingress.yaml
      - sed -i -e "s@SERVICE_NAME@$SERVICE_NAME_PRODUCTION@" k8s/service.yaml
      - sed -i -e "s@DOCKER_IMAGE@$IMAGE@" k8s/deploy.yaml
      - kubectl delete secret wildcard-bending-the-rules-nl-secret || true
      - kubectl delete secret gitlab-docker-registry || true
      - kubectl create secret docker-registry gitlab-docker-registry --docker-server=registry.bendingtherules.nl --docker-username=kubernetes --docker-password=${KUBERNETES_DOCKER_PASSWORD} --docker-email=kubernetes@bendingtherules.nl -n ${KUBE_NAMESPACE}
      - kubectl replace -f k8s/deploy.yaml || kubectl create -f k8s/deploy.yaml
      - kubectl apply   -f k8s/service.yaml
      - kubectl apply   -f k8s/ingress.yaml
      